MK_CFG_DIR = /home/y/share/make_cfg
include $(MK_CFG_DIR)/make.defs

EXETARGET = exmon
CSRC = exmon.c exmon_conf.c
CXXSRC = 

WARN +=
OPPFLAGS += -I/home/y/include/ncore
LDFLAGS = -L/home/y/lib
LDLIBS = -lncore

include $(MK_CFG_DIR)/make.rules
